sudo: true
language: node_js
node_js:
  - "12"

cache:
  directories:
    - $HOME/.npm
    - /usr/local/lib/node_modules

before_script:
  - npm install install

script:
  - hexo deploy

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: public
  target_branch: gh-pages
  on:
    branch: master
notifications:
  email:
    on_success: never
    on_failure: never